name: Capture Docker Logs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-logs:
    runs-on: ubuntu-latest  # Use an appropriate runner

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t get-logs-container .

      # Run Docker container for logs and capture them in a file
      - name: Run Docker Container for Logs
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock get-logs-container --logs > output-logs.txt

      # Optionally, display the logs in the GitHub Actions workflow logs
      - name: Show logs in GitHub Actions output
        run: |
          cat output-logs.txt

      # Optionally, upload the logs file as an artifact to GitHub
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-logs
          path: output-logs.txt
