name: Capture Docker Logs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  capture-logs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image (if Dockerfile is in a subdirectory 'docker')
      - name: Build Docker image
        run: |
          docker build -t get-logs-container -f examples/first-dockerfile/

      # Run Docker container in detached mode, get logs, and remove the container
      - name: Run Docker Container for Logs
        run: |
          container_id=$(docker run -d get-logs-container)  # Start container in detached mode
          docker logs $container_id > output-logs.txt        # Capture logs
          docker rm -f $container_id                         # Clean up the container

      # Optionally, display the logs in GitHub Actions workflow logs
      - name: Show logs in GitHub Actions output
        run: |
          cat output-logs.txt

      # Optionally, upload the logs file as an artifact to GitHub
      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-logs
          path: output-logs.txt
