name: Docker Logs Fetcher

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t get-logs-container examples/first-dockerfile/

      # Run the Docker container to fetch logs
      - name: Run Docker Container for Logs
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock get-logs-container --logs

      # Optional: Run the Docker container to fetch container info
      - name: Run Docker Container for Info
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock get-logs-container --info

